config/routes.rb
Fakebook::Application.routes.draw do
  resources :documents, :only => [ :index, :show, :update ] do
    get :search, :on => :collection
  end

  resources :tags, :only => :index do
    get :search, :on => :collection
  end

  resource :repository, :controller => 'repository'

  root :to => 'repository#new'
end

app/models/document.rb
require 'mongoid/document/taggable'

class Document
  include Mongoid::Document
  include Mongoid::Document::Taggable

  field :name,     :type => String
  field :size,     :type => Integer
  field :date,     :type => Time
  field :author,   :type => String
  field :revision, :type => Integer

  attr_accessible :name, :size, :date, :author, :revision

# scope :alphabetical, order_by(:name, :asc)
  scope :alphabetical, asc(:name)
  scope :new_or_changed_since, ->(date) {
#   where(:date.gte => date).order_by(:name, :asc)
    where(:date.gte => date).asc(:name)
  }
  scope :named, ->(name) { where(:name => name) }

  # 1. update Document tags from UI
  # 2. save Document tags to repo
  # 3. update Document tags from repo
  # 4. save Document
  def update_tags(tags = nil)
    set_tags(tags)
    write_tags_to_repo
    read_tags_from_repo
    save!
  end

  def set_tags(tags = nil)
    if tags.present?
      self.tag_list = Array(tags).map(&:titleize).uniq.join(', ')
    else
      self.tags = nil
    end
  end

  def write_tags_to_repo
    Repository.set_tags(self)
  end

  def read_tags_from_repo
    tag_props = Repository.get_tags(name)
    set_tags(eval(tag_props))
  end

  # ignore file extension in name
  def self.search(term)
    file_extension = /\..+$/
    contains_term  = /#{term}/i
#   where(:name => contains_term).order_by(:name, :asc).select{ |doc|
    where(:name => contains_term).asc(:name).select{ |doc|
      doc.name.gsub(file_extension, '') =~ contains_term
    }
  end

  def self.without_tags
#   order_by(:name, :asc).select{ |d| d.tags.blank? }
    asc(:name).select{ |d| d.tags.blank? }
  end

  # return mutating entries wrapped as Documents
  def self.status(options = {})
    Repository.status.split(/\n/).map { |line|
      # " M      /path/to/repository/Document Name.pdf\n"
      named(line.split(/\//).last).first
    }.sort_by(&:name)
  end

  # return reverted entries wrapped as Documents
  def self.revert
    Repository.revert.split(/\n/).map { |line|
      # "Reverted '/path/to/repository/Document Name.pdf'\n"
      named(line.split(/\//).last.gsub(/'$/, '')).first
    }
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    date = 6.weeks.ago.to_date
    @document_groups = {
      'unidentified' => Document.without_tags,
      "new or different since #{date.to_s(:mdy)}" => Document.new_or_changed_since(date)
    }
    @document_groups.merge!(Document.alphabetical.group_by { |doc| doc.name.upcase[0..0] })
  end

  def search
    documents = if params[:term].present?
                  Document.search(params[:term]).map{ |doc| { :value => doc.name, :id => doc.id } }
                else
                  []
                end
    render :json => documents
  end

  def show
    @document = Document.find(params[:id])
    @tag_groups = Document.tags.sort.group_by { |tag| tag.upcase[0..0] }
  end

  def update
    show
    tags = params[:document][:tags] rescue nil
    # synchronous svn - SLOW
    @document.update_tags(tags)
    respond_to do |format|
      format.html {
        flash[:notice] = "tags = [ #{@document.tag_list} ] "
        render :show
      }
      format.js {
        render :json => { :name => @document.name, :tags => @document.tag_list }
      }
    end
  end
end

app/views/documents/_search.html.erb
<input type='text' id='search_term' placeholder='s e a r c h &middot; t i t l e' />
<script type='text/javascript'>
  $(function() {
    $( '#search_term' ).autocomplete({
      source: '<%= search_documents_path %>',
      minLength: 2,
      select: function(event, ui) {
        window.location = '/documents/' + ui.item.id;
      }
    });
  });
</script>

app/views/documents/index.html.erb
<div id="documents">
  <% @document_groups.each do |group| %>
    <h3><a href="#"><%= group.first %></a></h3>
    <ul>
      <% group.last.each do |doc| %>
        <li><%= link_to doc.name, document_path(doc) %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<script type="text/javascript">
  $(function() {
    $( '#documents' ).accordion({
      active: false,
      autoHeight: false,
      collapsible: true,
      navigation: true
    });
  });
</script>

app/views/documents/show.html.erb
<% if flash[:notice] %><p class='flash notice'><%= flash[:notice] %></p><% end %>

<fieldset class='document'>
  <legend><%= @document.name %></legend>
  <ul>
    <li><b>Date:</b> <%= @document.date %></li>
    <li><b>Author:</b> <%= @document.author %></li>
    <li><b>Revision:</b> <%= @document.revision %></li>
    <li><b>Size:</b> <%= @document.size %></li>
    <li>
    <b>Tags:</b><br />
      <input type='text' id='search_tags' placeholder='search tags' />
      <input type='text' id='add_new_tag' placeholder='add new tag' />
    </li>
  </ul>

  <%= form_for(@document) do |f| %>
    <div id='document_tag_fields'>
      <% if @document.tags.present? %>
        <% @document.tags.sort.each do |tag| %>
          <div class='field'>
            <input type='checkbox' name='document[tags][]' checked='checked' value='<%= tag %>' />
            <%= tag %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class='actions'>
      <%= f.submit 'o k' %>
      <%= link_to 'c a n c e l', documents_path %>
    </div>
  <% end %>
</fieldset>

<script type='text/javascript'>
$(function() {
  var $form = $( 'form.edit_document' ),
      $modified = $( '.modified' );

  $form.on( 'click', 'input:submit', function(event) {
    var $submit = $( this );

    $submit.val( 'p r o c e s s i n g' ).attr( 'disabled', 'disabled' );

    $( 'p.flash.notice' ).slideUp().remove();

    $.ajax({
      url: $form.attr( 'action' ),
      type: 'POST',
      data: $form.serialize(),
      dataType: 'json',
      success: function( data ) {
        $( '.document' ).before( '<p class="flash notice" style="display:none;" />' );
        $( 'p.flash.notice' ).html( 'TAGS = [' + data.tags + ']' ).slideDown();
        $submit.val( 'o k' ).removeAttr( 'disabled' );
        $modified.showStatus({ url: '<%= repository_path %>' });
      }
    });

    return false;
  });
});
</script>

<div id='grouped_tags'>
<% @tag_groups.each do |group| %>
  <h3><a href='#'><%= group.first %></a></h3>
  <div>
  <% group.last.each do |tag| %>
    <input type='checkbox' <%= @document.tags && @document.tags.include?(tag) ? 'checked="checked"' : '' %> value='<%= tag %>' /><%= tag %> &middot;
  <% end %>
  </div>
<% end %>
</div>

<script type='text/javascript'>
  $(function() {
    var $source = $('#grouped_tags'),
        $target = $('#document_tag_fields'),
        $add_new_tag = $('#add_new_tag'),
        $search_tags = $('#search_tags');

    function add_tag(text) {
      $target.append('<div class="field"><input type="checkbox" name="document[tags][]" checked="checked" value="' + text + '" />' + text + '</div>');
    }

    $add_new_tag.keypress(function(e) {
      if (e.which == 13) {
        var e = $(this);
        var tag = $.trim(e.val());
        if (tag.match(/\S/)) {
          add_tag(tag);
          e.val('').end().blur();
        }
      }
    });

    $search_tags.autocomplete({
      source: '<%= search_tags_path %>',
      minLength: 2,
      select: function(event, ui) {
        add_tag(ui.item.value);
      },
      close: function(event, ui) {
        $search_tags.val('');
      }
    });

    $source.accordion({
      active: false,
      autoHeight: false,
      collapsible: true,
      navigation: true
    });

    $source.on('click', 'input:checkbox', function() {
      var e = $(this);
      if (e.is(':checked')) {
        add_tag(e.val());
      } else {
        $target.find('input:checkbox[value="' + e.val() + '"]').each(function() {
          $(this).closest('div').remove();
        });
      }
    });

    $target.on('click', 'input:checkbox', function() {
      var e = $(this);
      $source.find('input:checked[value="' + e.val() + '"]').each(function() {
        $(this).attr('checked', false);
      });
      e.closest('div').remove();
    });
  });
</script>