config/routes.rb
Fakebook::Application.routes.draw do
  resources :documents, :only => [ :index, :show, :update ] do
    get :search, :on => :collection
  end

  resources :tags, :only => :index do
    get :search, :on => :collection
  end

  resource :repository, :controller => 'repository'

  root :to => 'repository#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>f a k e b o o k . o r g</title>
<%= stylesheet_link_tag    'application' %>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>
<script type='text/javascript'>
$(function() {
  if (typeof EventSource === 'undefined') {
    alert('Please use a real browser.');
    location = 'http://caniuse.com/eventsource';
  }
});
</script>
<% unless %w(repository).include?(params[:controller]) %>
<script type='text/javascript'>
$(function() {
  $( '.modified' ).showStatus({ url: '<%= repository_path %>' });
});
</script>
<% end %>
<%= yield :javascript %>
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='eleven columns'>
        <h1>f a k e b o o k . o r g</h1>
      </div>
      <div class='one columns'>
        <span>[ <%= exploded(@remote_user) %> ]</span>
      </div>
    </div>
    <div class='row'>
      <div class='nine columns'>
<%= yield %>
      </div>
      <div class='three columns'>
        <div class='row'>
          <ul class='nav'>
            <li><%= request.fullpath == '/repository/new' ? _initialize : link_to(_initialize, new_repository_path) %></li>
            <li><%= request.fullpath == '/documents' ? by_title : link_to(by_title, documents_path) %></li>
            <li><%= request.fullpath == '/tags' ? by_tag : link_to(by_tag, tags_path) %></li>
            <li><%= render 'documents/search' %></li>
            <li><%= request.fullpath == '/repository/edit' ? save_changes : link_to(save_changes, edit_repository_path) %></li>
            <li class='modified' style='display:none'>
              <ol></ol>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</body>
</html>